### ISSUE TITLE
Improvements Checklist

### ISSUE THREAD

**Issue by purrcat259** [The-Sovereignty/SovereigntyWebsite#2]
- [ ] Use standard naming conventions for IDs and classes
- [ ] Convert GIF to HTML5 videos
- [ ] Mobile friendly improvements
- [ ] Float center image in the middle when viewport width changes
- [ ] Improve colour palette (needs some more contrast)
- [ ] Minify background images
